### ISSUE TITLE
ログイン、一覧、入力画面デザイン案

### ISSUE THREAD

**Issue by sae1116** [g59/rate#1]
・ログイン画面
・評価入力画面
・一覧画面（順位表示）

評価画面は今の自分の認識が合っているのか不安なので2案載せます。
デザインはもっとゴリゴリでいいやつないか引き続き検討しますが一旦方向のすり合わせをお願いしたいです。
また、レーティングのスライダーと星はどっちにしようかまだ悩んでいる段階なので2つ表示されていますが実際は統一したものになります。

# ログイン
![rate -1- -3](https://user-images.githubusercontent.com/10301344/38125772-e7525ce8-3426-11e8-8c35-c08e967af078.png)
# 昨日までの認識（マイページ的なのがあるのかと勘違いしてたやつ）
![rate -1- -2](https://user-images.githubusercontent.com/10301344/38125784-fde6ae0a-3426-11e8-8ec4-0cba11664bb8.png)

# 今日改めて聞いて作成し直したやつ
![rate -1- -7](https://user-images.githubusercontent.com/10301344/38125789-033f0f96-3427-11e8-8796-dbe4231f324b.png)
![rate -1- -6](https://user-images.githubusercontent.com/10301344/38125788-031be9bc-3427-11e8-9a7e-9317fae6dca3.png)

**Comment by 9renpoto** [comment]
一旦大枠は完了ということで閉じる
