### ISSUE TITLE
firebase github 認証

### ISSUE THREAD

**Issue by 9renpoto** [g59/rate#35]
github org にいるメンバーだけ許可するとかそういうことがしたい感じ

**Comment by taka-sho** [comment]
## やること
- GitHub経由で認証。( `email` と `password`)
- GitHub API V3 経由でデータの取得
  - `GET /orgs/:org/members` : orgに入っている人のリスト
- Routing
  - 期待するOrgMemberでログインしていたら `/gh/:id/mypage` 
  - 未ログイン or OrgMember出ないならば `403` ?

**Comment by taka-sho** [comment]
## 現状

- `next-routes` にナビゲーションガードが実装されていない
  - アカウントごとにページを生成するのでこれがないと大変厳しい.代用案を探す？
- github経由で認証する場合、用意しているformにmail&passwordの方式ではなく、認証画面に飛ばし、そこでmail&password。
  - ログイン画面はボタン１つにする方向で。
- GitHub Organizationの選択をどのタイミングでするか。認証後直後？
- Organization内での書く個人のPermissionの構造が（主に経験がないと言う意味で）難しい。要勉強

---

巻きで作業をしなければ...

**Comment by taka-sho** [comment]
- `next/router` にナビゲーションガードがあった。
- `firebase` のauthでgithubを利用したのち、tokenが発行され、それを使えばgithubに直接認証できる。
  - `GraphQL` でGitHub APIを叩く。
  - organizationでの各個人のpermissionをどう叩くか

**Comment by 9renpoto** [comment]
あれ、 next-routesはnavigation guardないのか
表示されるconponentを表示しないよう分岐するしかないのかな
